version: "3.9"

services:
  backend:
    image: user:1.0
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
    depends_on:
      - db
    networks:
      - app-network

  go-backend:
    image: product:1.0
    container_name: go-product-service
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

  frontend:
    image: front:1.0
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - go-backend
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
