apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: {{ .Values.user.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: {{ .Values.user.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db:5432/mydb
            - name: REDIS_URL
              value: redis://redis:6379/0
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: {{ .Values.user.namespace }}
spec:
  selector:
    app: user
  ports:
    - port: 8000
